name:                error-context
version:             0.2.0.0
github:              "mtesseract/error-context"
license:             BSD3
author:              "Moritz Clasmeier"
maintainer:          "mtesseract@silverratio.net"
copyright:           "(c) 2018 Moritz Clasmeier"
synopsis:            Provides API for enriching errors with contexts
category:            Control, Error Handling

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/mtesseract/error-context#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- text
- exceptions
- safe-exceptions
- unliftio-core
- resourcet
- monad-logger
- katip
- aeson
- unordered-containers

ghc-options:
- -Wall

library:
  source-dirs: src

tests:
  error-context-tests:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -g
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - error-context
    - tasty
    - tasty-hunit
    - safe-exceptions
    - aeson
